"""
Słownik poprawek: polskie słowa zapisane bez znaków diakrytycznych.

Klucze to pełne wyrazy (dopasowanie z granicami słów), więc "pytan" nie
zepsuje słowa "pytania". Wielkość liter jest odtwarzana automatycznie:
"zrodlo" -> "źródło", "Zrodlo" -> "Źródło", "PODGLAD" -> "PODGLĄD".
"""

WORD_MAP = {
    # A-C
    "bezblednie": "bezbłędnie", "bezposrednio": "bezpośrednio",
    "biale": "białe", "bialego": "białego", "bialy": "biały", "bialym": "białym",
    "biezacy": "bieżący", "biezacych": "bieżących", "biezacym": "bieżącym",
    "blad": "błąd", "bledow": "błędów", "bledy": "błędy", "bledu": "błędu",
    "byc": "być", "byl": "był", "byla": "była", "byly": "były",
    "caly": "cały", "ciagly": "ciągły", "czcionke": "czcionkę",
    # D
    "dalo": "dało", "dlugo": "długo", "dluzej": "dłużej",
    "dol": "dół", "dolacza": "dołącza", "dolaczony": "dołączony",
    "dolaczone": "dołączone", "dolacz": "dołącz",
    "domyslany": "domyślany", "domyslne": "domyślne", "domyslnie": "domyślnie",
    "domyslny": "domyślny", "domyslnym": "domyślnym", "domyslnymi": "domyślnymi",
    "dziala": "działa", "dzialaja": "działają", "dzialajacych": "działających",
    "dzialania": "działania", "dzialanie": "działanie", "dzieki": "dzięki",
    "duza": "duża", "duze": "duże", "duzej": "dużej", "duzy": "duży",
    # F-J
    "faze": "fazę", "falszywe": "fałszywe", "falszywek": "fałszywek",
    "falszywych": "fałszywych", "falszywy": "fałszywy",
    "gora": "góra", "gorna": "górna", "gory": "góry",
    "imie": "imię", "jasnosci": "jasności", "jesli": "jeśli",
    "jezyk": "język", "jezyka": "języka", "jezyki": "języki", "jezyku": "języku",
    # K
    "kamere": "kamerę", "karte": "kartę", "katy": "kąty", "kat": "kąt",
    "kazda": "każda", "kazde": "każde", "kazdego": "każdego",
    "kazdej": "każdej", "kazdym": "każdym",
    "klatke": "klatkę", "kolejnosc": "kolejność", "kolejnosci": "kolejności",
    "koncowy": "końcowy", "koncu": "końcu",
    "krawedz": "krawędź", "krawedzi": "krawędzi", "krawedziach": "krawędziach",
    "krawedzie": "krawędzie", "krotka": "krótka", "krotki": "krótki",
    "ksztaltow": "kształtów", "ksztaltu": "kształtu",
    "ktora": "która", "ktore": "które", "ktorego": "którego",
    "ktorej": "której", "ktorych": "których", "ktorym": "którym", "ktory": "który",
    # L
    "lezy": "leży", "liscie": "liście", "liste": "listę",
    "litere": "literę", "lacznie": "łącznie",
    # M
    "male": "małe", "maly": "mały", "mala": "mała",
    "miedzy": "między", "migotala": "migotała", "minal": "minął",
    "moge": "mogę", "moze": "może", "mozesz": "możesz", "mozna": "można",
    "mozliwe": "możliwe", "mozliwosc": "możliwość",
    # N
    "naglowek": "nagłówek", "naglowku": "nagłówku",
    "najwyzej": "najwyżej", "nakladane": "nakładane", "nakladamy": "nakładamy",
    "napisal": "napisał", "naprawde": "naprawdę",
    "narozniki": "narożniki", "naroznikami": "narożnikami",
    "narysowac": "narysować", "nastepne": "następne", "nastepnego": "następnego",
    "nastepnie": "następnie", "nastepny": "następny",
    "nawiazanie": "nawiązanie", "nazwe": "nazwę",
    "niedostepny": "niedostępny", "niedostepna": "niedostępna",
    "niezalezna": "niezależna", "niezalezne": "niezależne",
    "niezaleznie": "niezależnie", "niezalezny": "niezależny",
    "niz": "niż",
    # O
    "obiektow": "obiektów", "obrocil": "obrócił", "obrocona": "obrócona",
    "obrocone": "obrócone", "obroc": "obróć", "obrot": "obrót",
    "obslugiwane": "obsługiwane", "obsluguje": "obsługuje", "obsluga": "obsługa",
    "odczytow": "odczytów", "odleglosci": "odległości",
    "odpowiadaja": "odpowiadają", "odpowiedz": "odpowiedź",
    "odpowiedzia": "odpowiedzią",
    "odslania": "odsłania", "odswiez": "odśwież", "odswiezyc": "odświeżyć",
    "odwrotnosc": "odwrotność", "okladki": "okładki",
    "okraglych": "okrągłych", "opoznienie": "opóźnienie",
    "opoznienia": "opóźnienia", "opoznien": "opóźnień",
    "ostatecznosc": "ostateczność", "otworzyc": "otworzyć",
    # P
    "pamieci": "pamięci", "pamiecia": "pamięcią",
    "petla": "pętla", "petle": "pętlę", "petli": "pętli",
    "pierwszenstwo": "pierwszeństwo", "plikow": "plików",
    "plotna": "płótna", "plynna": "płynna", "plynnie": "płynnie",
    "podawac": "podawać", "podglad": "podgląd", "podgladem": "podglądem",
    "podgladu": "podglądu", "podgladzie": "podglądzie",
    "podnies": "podnieś", "podpowiedz": "podpowiedź",
    "podreczna": "podręczna", "podwojnym": "podwójnym",
    "pokaz": "pokaż", "pokazywac": "pokazywać",
    "polaczenia": "połączenia", "polaczenie": "połączenie",
    "polaczen": "połączeń", "polecen": "poleceń",
    "pomaranczowy": "pomarańczowy", "pomin": "pomiń",
    "posrednie": "pośrednie", "poszczegolnych": "poszczególnych",
    "potrafia": "potrafią", "potwierdz": "potwierdź",
    "powiodl": "powiódł", "powstaja": "powstają",
    "pozostaly": "pozostały", "prog": "próg",
    "prowadzacy": "prowadzący", "przegladarce": "przeglądarce",
    "przegladarke": "przeglądarkę", "przegladarki": "przeglądarki",
    "przejsc": "przejść", "przejscia": "przejścia",
    "przelacznik": "przełącznik", "przelacz": "przełącz",
    "przeplyw": "przepływ",
    "przeslany": "przesłany", "przyciecie": "przycięcie",
    "przykladowe": "przykładowe", "przykladowy": "przykładowy",
    "punktow": "punktów", "pytan": "pytań",
    # Q-R
    "quizow": "quizów", "recznych": "ręcznych", "recznie": "ręcznie",
    "rogow": "rogów", "rozdzial": "rozdział",
    "rozdzielczosc": "rozdzielczość", "rozklad": "rozkład",
    "rozkladu": "rozkładu", "rozstep": "rozstęp",
    # S
    "sie": "się", "skladaj": "składaj", "skroty": "skróty",
    "slaby": "słaby", "slabym": "słabym", "slownik": "słownik",
    "slownika": "słownika", "slupki": "słupki", "sluzy": "służy",
    "smieci": "śmieci", "sprawdz": "sprawdź", "sprobuj": "spróbuj",
    "srodek": "środek", "srodku": "środku", "srodowisko": "środowisko",
    "srodowiska": "środowiska", "stad": "stąd", "stalej": "stałej",
    "stale": "stałe", "strone": "stronę", "strumien": "strumień",
    "sygnalu": "sygnału", "szalwia": "szałwia",
    # T
    "tla": "tła", "tlumaczenia": "tłumaczenia", "tlumaczen": "tłumaczeń",
    "trwale": "trwałe", "tworze": "tworzę",
    # U
    "uczen": "uczeń", "uczniow": "uczniów", "udalo": "udało",
    "uruchamiajacy": "uruchamiający", "uruchomic": "uruchomić",
    "ustalil": "ustalił", "ustawien": "ustawień",
    "usun": "usuń", "uzycie": "użycie", "uzyty": "użyty",
    "uzywaja": "używają", "uzywane": "używane", "uzywa": "używa",
    "uzyj": "użyj", "uzywac": "używać",
    # W
    "watek": "wątek", "watkowo": "wątkowo", "watku": "wątku",
    "wazne": "ważne", "wewnatrz": "wewnątrz",
    "wiec": "więc", "wiecej": "więcej", "wiekszosc": "większość",
    "wielokrotnosc": "wielokrotność",
    "wlaczone": "włączone", "wlaczony": "włączony", "wlacza": "włącza",
    "wlasna": "własna", "wlasnie": "właśnie", "wlasny": "własny",
    "wlasnym": "własnym", "wlasnej": "własnej",
    "wplywa": "wpływa", "wskaznik": "wskaźnik",
    "wspolna": "wspólna", "wspolne": "wspólne", "wspolny": "wspólny",
    "wspolrzednych": "współrzędnych", "wspolrzednymi": "współrzędnymi",
    "wspolrzedne": "współrzędne",
    "wybor": "wybór", "wyczysc": "wyczyść",
    "wygladaja": "wyglądają", "wyjscie": "wyjście",
    "wyjsciowy": "wyjściowy", "wyjsciowym": "wyjściowym",
    "wykryc": "wykryć", "wylacznie": "wyłącznie",
    "wynikow": "wyników", "wyraznego": "wyraźnego",
    "wyrazniejszego": "wyraźniejszego", "wyrazniejszy": "wyraźniejszy",
    "wyslac": "wysłać", "wysokosci": "wysokości",
    "wyswietlania": "wyświetlania", "wyswietla": "wyświetla",
    "wywolywane": "wywoływane", "wywrocic": "wywrócić", "wzor": "wzór",
    # Z
    "zaimportowac": "zaimportować", "zakladka": "zakładka",
    "zakladki": "zakładki", "zalezne": "zależne",
    "zaleznosci": "zależności", "zamrazamy": "zamrażamy",
    "zamykac": "zamykać", "zarowno": "zarówno",
    "zastepczy": "zastępczy", "zastepcza": "zastępcza",
    "zeby": "żeby", "zeton": "żeton", "zetonach": "żetonach",
    "zetony": "żetony", "zdjecie": "zdjęcie", "zdjecia": "zdjęcia",
    "zmien": "zmień", "znakow": "znaków",
    "zostalaby": "zostałaby", "zostalby": "zostałby",
    "zrodel": "źródeł", "zrodla": "źródła", "zrodlem": "źródłem",
    "zrodlo": "źródło", "zrodlowego": "źródłowego", "zrodlowy": "źródłowy",
    "zwykla": "zwykła",
    # drugie przejście — uzupełnienia po przeglądzie pozostałych tokenów
    "importuja": "importują", "markerow": "markerów",
    "przyciskow": "przycisków", "sciezek": "ścieżek", "sciezki": "ścieżki",
    "sciezka": "ścieżka", "sciezke": "ścieżkę",
    "wartosciami": "wartościami", "trafialy": "trafiały",
    "kolorow": "kolorów", "znajduja": "znajdują",
    "sluza": "służą", "moga": "mogą",
    "wygladaj": "wyglądaj", "beda": "będą", "bedzie": "będzie",
    "jezeli": "jeżeli", "wlasciwie": "właściwie", "chcialbys": "chciałbyś",
    # krótkie wyrazy (uwaga: "ze" to poprawny przyimek — nie zmieniamy go)
    "sa": "są", "juz": "już", "tez": "też", "az": "aż",
    "ktos": "ktoś", "cos": "coś", "jakis": "jakiś", "czesto": "często",
    "wszedzie": "wszędzie", "dwoch": "dwóch", "prosze": "proszę",
    "musze": "muszę", "bede": "będę",
}

# Słowa, których NIE wolno ruszać (nazwy plików, miasta w danych, kod).
NEVER_TOUCH = {"przyklad", "przyklad.json", "wyniki", "karty", "quiz",
               "pozna", "krak", "gda", "stolic"}
